use_default_settings: true

general:
  instance_name: "Starlen Web Research"

search:
  safe_search: 1
  formats:
    - html
    - json

server:
  secret_key: "${SEARXNG_SECRET}"
  limiter: false
  image_proxy: true
