"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type User = { id: string; email: string; is_admin: boolean; is_active: boolean };
type UsageUser = User & { input_tokens: number; output_tokens: number; total_tokens: number; request_count: number; last_activity: string | null };
type Overview = { user_count: number; active_user_count: number; request_count: number; input_tokens: number; output_tokens: number; total_tokens: number; users: UsageUser[] };
type ApiKey = { id: string; user_id: string; name: string; key_prefix: string; expires_at: string | null; last_used_at: string | null; revoked_at: string | null };
type Analytics = { days: number; active_key_count: number; revoked_key_count: number; daily: { day: string; request_count: number; input_tokens: number; output_tokens: number }[]; models: { model: string; request_count: number; total_tokens: number; average_duration_ms: number }[]; recent: { id: string; email: string; model: string; input_tokens: number; output_tokens: number; status: string; created_at: string }[] };
type ManagedModel = { model: string; enabled: boolean };

const base = (process.env.NEXT_PUBLIC_API_BASE_URL || "/api/gateway").replace(/\/$/, "");
const compact = new Intl.NumberFormat("en", { notation: "compact", maximumFractionDigits: 1 });

function Icon({ name }: { name: "grid" | "users" | "key" | "chart" | "settings" | "book" | "chat" | "refresh" | "logout" | "plus" | "more" }) {
  const paths = {
    grid: <><rect x="3" y="3" width="7" height="7" rx="1" /><rect x="14" y="3" width="7" height="7" rx="1" /><rect x="3" y="14" width="7" height="7" rx="1" /><rect x="14" y="14" width="7" height="7" rx="1" /></>,
    users: <><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" /><circle cx="9" cy="7" r="4" /><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75" /></>,
    key: <><circle cx="7.5" cy="15.5" r="4.5" /><path d="m21 2-9.8 9.8M15 6l3 3M18 3l3 3" /></>,
    chart: <><path d="M3 3v18h18" /><path d="m7 16 4-5 3 3 6-8" /></>,
    settings: <><circle cx="12" cy="12" r="3" /><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.12 2.12-.06-.06A1.7 1.7 0 0 0 15.74 18a1.7 1.7 0 0 0-1.03 1.55V20h-3v-.45A1.7 1.7 0 0 0 10.68 18a1.7 1.7 0 0 0-1.88 1l-.06.06-2.12-2.12.06-.06A1.7 1.7 0 0 0 7 15a1.7 1.7 0 0 0-1.55-1.03H5v-3h.45A1.7 1.7 0 0 0 7 9.94a1.7 1.7 0 0 0-.32-1.88l-.06-.06 2.12-2.12.06.06A1.7 1.7 0 0 0 10.68 7a1.7 1.7 0 0 0 1.03-1.55V5h3v.45A1.7 1.7 0 0 0 15.74 7a1.7 1.7 0 0 0 1.88-1.06l.06-.06L19.8 8l-.06.06A1.7 1.7 0 0 0 19.4 10a1.7 1.7 0 0 0 1.55 1.03H21v3h-.05A1.7 1.7 0 0 0 19.4 15Z" /></>,
    book: <><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20" /><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2Z" /></>,
    chat: <path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5Z" />,
    refresh: <><path d="M21 12a9 9 0 0 1-15.2 6.5L3 16" /><path d="M3 21v-5h5M3 12A9 9 0 0 1 18.2 5.5L21 8" /><path d="M21 3v5h-5" /></>,
    logout: <><path d="M10 17l5-5-5-5" /><path d="M15 12H3" /><path d="M21 19V5a2 2 0 0 0-2-2h-6" /></>,
    plus: <><path d="M12 5v14M5 12h14" /></>,
    more: <><circle cx="5" cy="12" r="1" fill="currentColor" /><circle cx="12" cy="12" r="1" fill="currentColor" /><circle cx="19" cy="12" r="1" fill="currentColor" /></>,
  };
  return <svg viewBox="0 0 24 24" aria-hidden="true" className="admin-icon">{paths[name]}</svg>;
}

export default function AdminDashboard() {
  const router = useRouter();
  const [token, setToken] = useState(""); const [me, setMe] = useState<User | null>(null);
  const [overview, setOverview] = useState<Overview | null>(null); const [analytics, setAnalytics] = useState<Analytics | null>(null);
  const [models, setModels] = useState<ManagedModel[]>([]); const [keys, setKeys] = useState<ApiKey[]>([]);
  const [days, setDays] = useState(30); const [status, setStatus] = useState("Loading control centre…");
  const [newEmail, setNewEmail] = useState(""); const [newPassword, setNewPassword] = useState("");
  const [selectedUser, setSelectedUser] = useState(""); const [keyName, setKeyName] = useState("Production integration"); const [expiry, setExpiry] = useState("90"); const [newKey, setNewKey] = useState("");
  const headers = useMemo(() => ({ Authorization: `Bearer ${token}`, "Content-Type": "application/json" }), [token]);
  const users = useMemo(() => [...(overview?.users || [])].sort((a, b) => b.total_tokens - a.total_tokens), [overview]);

  const request = async (path: string, init: RequestInit = {}) => {
    const response = await fetch(`${base}${path}`, { ...init, headers: { ...headers, ...init.headers } });
    const body = response.status === 204 ? null : await response.json().catch(() => null);
    if (!response.ok) throw new Error(body?.detail || "Request failed"); return body;
  };
  const load = async () => { try {
    const [nextOverview, nextAnalytics, nextModels, nextKeys] = await Promise.all([request("/admin/overview"), request(`/admin/analytics?days=${days}`), request("/admin/models"), request("/admin/api-keys")]);
    setOverview(nextOverview); setAnalytics(nextAnalytics); setModels(nextModels); setKeys(nextKeys); setSelectedUser((value) => value || nextOverview.users[0]?.id || ""); setStatus(`Synced ${new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}`);
  } catch (error) { setStatus(`Could not refresh: ${(error as Error).message}`); } };
  const logout = () => { sessionStorage.removeItem("ollama_gateway_token"); sessionStorage.removeItem("ollama_gateway_user"); router.replace("/login"); };
  const toggleUser = async (user: UsageUser) => { try { await request(`/admin/users/${user.id}`, { method: "PATCH", body: JSON.stringify({ is_active: !user.is_active }) }); setStatus(`${user.email} ${user.is_active ? "suspended" : "restored"}.`); await load(); } catch (error) { setStatus((error as Error).message); } };
  const toggleModel = async (model: ManagedModel) => { try { await request(`/admin/models/${encodeURIComponent(model.model)}`, { method: "PUT", body: JSON.stringify({ enabled: !model.enabled }) }); setStatus(`${model.model} ${model.enabled ? "disabled" : "enabled"}.`); await load(); } catch (error) { setStatus((error as Error).message); } };
  const createUser = async () => { try { const created = await request("/admin/users", { method: "POST", body: JSON.stringify({ email: newEmail, password: newPassword }) }); setNewEmail(""); setNewPassword(""); setSelectedUser(created.id); setStatus(`${created.email} was created.`); await load(); } catch (error) { setStatus((error as Error).message); } };
  const createKey = async () => { try { const created = await request("/admin/api-keys", { method: "POST", body: JSON.stringify({ user_id: selectedUser, name: keyName, expires_in_days: Number(expiry) || undefined }) }); setNewKey(created.api_key); setStatus("Key created. Copy it now; it cannot be viewed again."); await load(); } catch (error) { setStatus((error as Error).message); } };
  const revokeKey = async (id: string) => { if (!window.confirm("Revoke this API key?")) return; try { await request(`/admin/api-keys/${id}`, { method: "DELETE" }); setStatus("API key revoked."); await load(); } catch (error) { setStatus((error as Error).message); } };

  useEffect(() => { const saved = sessionStorage.getItem("ollama_gateway_token"); if (!saved) { router.replace("/login"); return; } void (async () => { try { const response = await fetch(`${base}/auth/me`, { headers: { Authorization: `Bearer ${saved}` } }); const current = await response.json(); if (!response.ok || !current.is_admin) { router.replace("/chat"); return; } setMe(current); setToken(saved); } catch { logout(); } })(); }, [router]);
  useEffect(() => { if (token) void load(); }, [token, days]);
  if (!me) return <main className="admin-loading">Verifying administrator access…</main>;

  const nav = [{ href: "/", label: "Overview", icon: "grid" as const }, { href: "/users", label: "People", icon: "users" as const }, { href: "/api-keys", label: "API access", icon: "key" as const }, { href: "/analytics", label: "Usage & limits", icon: "chart" as const }, { href: "/admin/settings", label: "Settings", icon: "settings" as const }];
  return <main className="admin-workspace">
    <aside className="admin-sidebar"><Link href="/" className="admin-brand"><img src="/icon.svg" alt="Starlen" /><span>starlen</span></Link><p className="admin-section-label">Workspace</p><nav>{nav.map((item) => <Link key={item.href} href={item.href} className={item.href === "/" ? "active" : ""}><Icon name={item.icon} />{item.label}</Link>)}</nav><p className="admin-section-label admin-spaced">Support</p><nav><Link href="/documentation"><Icon name="book" />Documentation</Link><Link href="/chat"><Icon name="chat" />Open workspace</Link></nav><div className="admin-sidebar-footer"><div className="admin-profile"><span>{me.email.slice(0, 1).toUpperCase()}</span><div><b>{me.email.split("@")[0]}</b><small>Administrator</small></div></div><button onClick={logout} aria-label="Sign out"><Icon name="logout" /></button></div></aside>
    <div className="admin-main"><header className="admin-topbar"><div><p className="eyebrow">Administration</p><h1>Good afternoon, {me.email.split("@")[0]}</h1><p className="admin-subtitle">A clear view of your AI workspace and its access.</p></div><div className="admin-top-actions"><span className="sync-status"><i />{status}</span><button className="button-quiet" onClick={() => void load()}><Icon name="refresh" />Refresh</button><Link className="button-primary" href="/users"><Icon name="plus" />Add user</Link></div></header>
      <section className="admin-metrics">{overview && <><Metric label="Total users" value={overview.user_count} note={`${overview.active_user_count} active`} /><Metric label="Requests" value={compact.format(overview.request_count)} note={`Last ${days} days`} /><Metric label="Tokens processed" value={compact.format(overview.total_tokens)} note={`${overview.request_count ? compact.format(Math.round(overview.total_tokens / overview.request_count)) : 0} per request`} /><Metric label="Active API keys" value={analytics?.active_key_count ?? "–"} note={`${analytics?.revoked_key_count ?? 0} revoked`} /></>}</section>
      <section className="admin-grid admin-primary-grid"><article className="admin-card"><div className="card-heading"><div><p className="card-kicker">Activity</p><h2>Request volume</h2></div><select value={days} onChange={(event) => setDays(Number(event.target.value))}><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option></select></div><Trend points={analytics?.daily || []} /></article><article className="admin-card"><div className="card-heading"><div><p className="card-kicker">System</p><h2>Model availability</h2></div><span className="count-chip">{models.filter((model) => model.enabled).length}/{models.length} live</span></div><div className="model-list">{models.slice(0, 4).map((model) => <div key={model.model}><span className={model.enabled ? "model-dot" : "model-dot muted"} /><b>{model.model}</b><button onClick={() => void toggleModel(model)}>{model.enabled ? "Enabled" : "Off"}</button></div>)}{!models.length && <p className="empty-note">No models available.</p>}</div><Link className="text-link" href="/users">Manage model access →</Link></article></section>
      <section className="admin-grid admin-operations-grid"><article className="admin-card table-card"><div className="card-heading"><div><p className="card-kicker">People</p><h2>Recent users</h2></div><Link className="text-link" href="/users">View all</Link></div><div className="table-wrap"><table><thead><tr><th>User</th><th>Usage</th><th>Last active</th><th /></tr></thead><tbody>{users.slice(0, 6).map((item) => <tr key={item.id}><td><div className="user-cell"><span>{item.email[0].toUpperCase()}</span><div><b>{item.email}</b><small className={item.is_active ? "good" : "bad"}>{item.is_active ? "Active" : "Suspended"}{item.is_admin ? " · Admin" : ""}</small></div></div></td><td>{compact.format(item.total_tokens)} <small>tokens</small></td><td>{item.last_activity ? new Date(item.last_activity).toLocaleDateString() : "Never"}</td><td>{!item.is_admin && <button className="row-action" onClick={() => void toggleUser(item)}>{item.is_active ? "Suspend" : "Restore"}</button>}</td></tr>)}{!users.length && <tr><td colSpan={4} className="empty-note">No users yet.</td></tr>}</tbody></table></div></article><article className="admin-card action-card"><div className="card-heading"><div><p className="card-kicker">Quick action</p><h2>Create a user</h2></div></div><p>Set up an account with a temporary password. Access and limits can be refined afterward.</p><label>Email<input type="email" value={newEmail} onChange={(event) => setNewEmail(event.target.value)} placeholder="name@company.com" /></label><label>Temporary password<input type="password" minLength={12} value={newPassword} onChange={(event) => setNewPassword(event.target.value)} placeholder="At least 12 characters" /></label><button className="button-primary full" disabled={!newEmail || newPassword.length < 12} onClick={() => void createUser()}><Icon name="plus" />Create account</button></article></section>
      <section className="admin-grid admin-bottom-grid"><article className="admin-card"><div className="card-heading"><div><p className="card-kicker">Security</p><h2>API key registry</h2></div><Link className="text-link" href="/api-keys">Manage keys</Link></div><div className="key-list">{keys.slice(0, 4).map((key) => <div key={key.id}><div><b>{key.name}</b><small>{key.key_prefix}… · {key.last_used_at ? "Used recently" : "Never used"}</small></div>{key.revoked_at ? <span className="key-revoked">Revoked</span> : <button className="row-action danger" onClick={() => void revokeKey(key.id)}>Revoke</button>}</div>)}{!keys.length && <p className="empty-note">No API keys issued.</p>}</div></article><article className="admin-card action-card compact-action"><div className="card-heading"><div><p className="card-kicker">Security</p><h2>Issue an API key</h2></div></div><label>Owner<select value={selectedUser} onChange={(event) => setSelectedUser(event.target.value)}>{users.map((item) => <option key={item.id} value={item.id}>{item.email}</option>)}</select></label><div className="form-pair"><label>Name<input value={keyName} onChange={(event) => setKeyName(event.target.value)} /></label><label>Expires<input type="number" min="0" value={expiry} onChange={(event) => setExpiry(event.target.value)} /></label></div><button className="button-primary full" disabled={!selectedUser || !keyName.trim()} onClick={() => void createKey()}><Icon name="key" />Issue key</button>{newKey && <div className="secret-box"><b>Copy this key now</b><code>{newKey}</code><button onClick={() => void navigator.clipboard.writeText(newKey)}>Copy to clipboard</button></div>}</article></section>
    </div>
  </main>;
}

function Metric({ label, value, note }: { label: string; value: string | number; note: string }) { return <article className="metric"><p>{label}</p><b>{value}</b><small>{note}</small></article>; }
function Trend({ points }: { points: { day: string; input_tokens: number; output_tokens: number }[] }) { const values = points.map((point) => point.input_tokens + point.output_tokens); const maximum = Math.max(...values, 1); return <div className="trend"><div className="trend-bars">{points.map((point, index) => <span key={point.day} title={`${point.day}: ${compact.format(values[index])} tokens`} style={{ height: `${Math.max((values[index] / maximum) * 100, 3)}%` }} />)}</div><div><span>{points[0]?.day || "No activity"}</span><span>Peak {compact.format(maximum)} tokens</span><span>{points.at(-1)?.day || ""}</span></div></div>; }
