"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type Model = { model: string; enabled: boolean };
type User = { id: string; email: string; is_active: boolean; is_admin: boolean };
type Overview = { users: User[] };
type ModelAccess = { model: string; enabled: boolean; inherited: boolean };
const base = (process.env.NEXT_PUBLIC_API_BASE_URL || "/api/gateway").replace(/\/$/, "");

export default function AdminSettingsPage() {
  const router = useRouter(); const [token, setToken] = useState(""); const [models, setModels] = useState<Model[]>([]); const [users, setUsers] = useState<User[]>([]);
  const [selectedUser, setSelectedUser] = useState(""); const [userModels, setUserModels] = useState<ModelAccess[]>([]); const [notice, setNotice] = useState("Loading workspace policy…");
  const [hideModelPicker, setHideModelPicker] = useState(false);
  const headers = useMemo(() => ({ Authorization: `Bearer ${token}`, "Content-Type": "application/json" }), [token]);
  const api = async (path: string, init: RequestInit = {}) => { const response = await fetch(`${base}${path}`, { ...init, headers: { ...headers, ...init.headers } }); const body = response.status === 204 ? null : await response.json().catch(() => null); if (!response.ok) throw new Error(body?.detail || "Request failed"); return body; };
  const load = async () => { try { const [nextModels, overview, settings] = await Promise.all([api("/admin/models"), api("/admin/overview"), api("/admin/settings")]); setModels(nextModels); setUsers(overview.users); setHideModelPicker(settings.hide_model_picker_for_users); setSelectedUser((current) => current || overview.users[0]?.id || ""); setNotice("Global model rules are active for every account."); } catch (error) { setNotice(`Could not load settings: ${(error as Error).message}`); } };
  const loadUserModels = async (userId: string) => { setSelectedUser(userId); if (!userId) return; try { setUserModels(await api(`/admin/users/${userId}/models`)); } catch (error) { setNotice(`Could not load user access: ${(error as Error).message}`); } };
  const toggleGlobal = async (model: Model) => { try { await api(`/admin/models/${encodeURIComponent(model.model)}`, { method: "PUT", body: JSON.stringify({ enabled: !model.enabled }) }); localStorage.setItem("starlen_model_policy_updated", Date.now().toString()); setNotice(`${model.model} is now ${model.enabled ? "hidden from the model picker" : "visible to users"}.`); await load(); if (selectedUser) await loadUserModels(selectedUser); } catch (error) { setNotice((error as Error).message); } };
  const toggleModelPicker = async () => { try { const settings = await api("/admin/settings", { method: "PUT", body: JSON.stringify({ hide_model_picker_for_users: !hideModelPicker }) }); setHideModelPicker(settings.hide_model_picker_for_users); localStorage.setItem("starlen_model_policy_updated", Date.now().toString()); setNotice(settings.hide_model_picker_for_users ? "The model picker is now hidden for standard users." : "The model picker is visible to standard users."); } catch (error) { setNotice((error as Error).message); } };
  const toggleUserModel = async (model: ModelAccess) => { if (!selectedUser) return; try { const updated = await api(`/admin/users/${selectedUser}/models/${encodeURIComponent(model.model)}`, { method: "PUT", body: JSON.stringify({ enabled: !model.enabled }) }); setUserModels((items) => items.map((item) => item.model === model.model ? updated : item)); setNotice(`Updated access for ${model.model}.`); } catch (error) { setNotice((error as Error).message); } };
  const toggleUser = async (user: User) => { try { await api(`/admin/users/${user.id}`, { method: "PATCH", body: JSON.stringify({ is_active: !user.is_active }) }); setNotice(`${user.email} ${user.is_active ? "suspended" : "restored"}.`); await load(); } catch (error) { setNotice((error as Error).message); } };
  useEffect(() => { const saved = sessionStorage.getItem("ollama_gateway_token"); if (!saved) { router.replace("/login"); return; } void (async () => { const response = await fetch(`${base}/auth/me`, { headers: { Authorization: `Bearer ${saved}` } }); const me = await response.json().catch(() => null); if (!response.ok || !me?.is_admin) { router.replace("/chat"); return; } setToken(saved); })(); }, [router]);
  useEffect(() => { if (token) void load(); }, [token]);
  useEffect(() => { if (token && selectedUser) void loadUserModels(selectedUser); }, [token, selectedUser]);
  return <main className="min-h-screen bg-[#10131a] p-4 text-slate-100 md:p-8"><div className="mx-auto max-w-6xl"><header className="flex flex-col gap-4 border-b border-white/10 pb-6 md:flex-row md:items-start md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[oklch(78.9%_0.154_211.53)]">Administration</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Workspace settings</h1><p className="mt-2 max-w-2xl text-sm text-slate-400">Set model visibility for everyone, make exceptions for individual accounts, and manage account access.</p></div><button onClick={() => void load()} className="rounded-lg border border-[oklch(78.9%_0.154_211.53_/_0.45)] bg-[oklch(78.9%_0.154_211.53_/_0.12)] px-4 py-2 text-sm font-semibold text-[oklch(86%_0.11_211.53)]">Refresh settings</button></header><p className="mt-4 text-sm text-slate-400">{notice}</p>
    <section className="mt-6 rounded-xl border border-white/10 bg-white/[.03] p-5"><div className="flex flex-col gap-2 border-b border-white/10 pb-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">Model visibility</h2><p className="mt-1 text-sm text-slate-400">Hide a model to remove it from the model picker for all accounts, including administrators.</p></div><span className="w-fit rounded-full bg-[oklch(78.9%_0.154_211.53_/_0.12)] px-3 py-1 text-xs text-[oklch(86%_0.11_211.53)]">{models.filter((model) => model.enabled).length} visible / {models.length}</span></div><div className="mt-4 flex items-center justify-between gap-4 rounded-lg border border-white/10 bg-black/10 p-4"><div><p className="text-sm font-semibold">Hide model picker for users</p><p className="mt-1 text-xs text-slate-400">Standard users can still use their assigned model, but cannot view or switch model names. Administrators keep the picker.</p></div><button onClick={() => void toggleModelPicker()} className={`shrink-0 rounded-md px-3 py-2 text-xs font-semibold ${hideModelPicker ? "bg-[oklch(78.9%_0.154_211.53_/_0.15)] text-[oklch(86%_0.11_211.53)]" : "bg-white/10 text-slate-200"}`}>{hideModelPicker ? "Enabled" : "Disabled"}</button></div><div className="mt-4 grid gap-3 md:grid-cols-2">{models.map((model) => <div key={model.model} className="flex items-center justify-between gap-4 rounded-lg border border-white/10 bg-black/10 p-4"><div className="min-w-0"><p className="truncate text-sm font-semibold">{model.model}</p><p className={`mt-1 text-xs ${model.enabled ? "text-emerald-300" : "text-slate-500"}`}>{model.enabled ? "Visible in the model picker" : "Hidden globally"}</p></div><button onClick={() => void toggleGlobal(model)} className={`shrink-0 rounded-md px-3 py-2 text-xs font-semibold ${model.enabled ? "bg-rose-400/10 text-rose-200 hover:bg-rose-400/20" : "bg-[oklch(78.9%_0.154_211.53_/_0.15)] text-[oklch(86%_0.11_211.53)]"}`}>{model.enabled ? "Hide model" : "Show model"}</button></div>)}{!models.length && <p className="text-sm text-slate-400">No installed models found.</p>}</div></section>
    <section className="mt-6 grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><article className="rounded-xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">Account control</h2><p className="mt-1 text-sm text-slate-400">Suspend or restore access without removing a user’s data.</p><div className="mt-4 max-h-[390px] space-y-2 overflow-auto">{users.map((user) => <div key={user.id} className="flex items-center justify-between gap-3 rounded-lg bg-black/10 p-3"><div className="min-w-0"><p className="truncate text-sm">{user.email}</p><p className={`mt-1 text-xs ${user.is_active ? "text-emerald-300" : "text-rose-300"}`}>{user.is_admin ? "Administrator · " : ""}{user.is_active ? "Active" : "Suspended"}</p></div>{!user.is_admin && <button onClick={() => void toggleUser(user)} className="rounded-md border border-white/10 px-3 py-1.5 text-xs text-slate-200 hover:bg-white/10">{user.is_active ? "Suspend" : "Restore"}</button>}</div>)}</div></article><article className="rounded-xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">Individual model access</h2><p className="mt-1 text-sm text-slate-400">Grant or block a model for one person. This rule overrides the global default for that user.</p><label className="mt-4 block text-sm text-slate-300">Select account<select value={selectedUser} onChange={(event) => void loadUserModels(event.target.value)} className="mt-2 w-full rounded-lg border border-white/10 bg-[#10131a] p-3 text-sm outline-none focus:border-[oklch(78.9%_0.154_211.53)]">{users.map((user) => <option key={user.id} value={user.id}>{user.email}</option>)}</select></label><div className="mt-4 grid gap-2 sm:grid-cols-2">{userModels.map((model) => <div key={model.model} className="flex items-center justify-between gap-3 rounded-lg bg-black/10 p-3"><div className="min-w-0"><p className="truncate text-sm">{model.model}</p><p className="mt-1 text-xs text-slate-500">{model.inherited ? "Global rule" : "Personal rule"}</p></div><button onClick={() => void toggleUserModel(model)} className={`rounded-md px-2.5 py-1.5 text-xs font-semibold ${model.enabled ? "bg-emerald-400/10 text-emerald-200" : "bg-rose-400/10 text-rose-200"}`}>{model.enabled ? "Allowed" : "Blocked"}</button></div>)}</div></article></section>
  </div></main>;
}
