"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type Skill = { id: string; name: string; description: string | null; instructions: string; is_published: boolean };
const base = (process.env.NEXT_PUBLIC_API_BASE_URL || "/api/gateway").replace(/\/$/, "");

export default function SkillsPage() {
  const router = useRouter(); const [token, setToken] = useState(""); const [skills, setSkills] = useState<Skill[]>([]); const [notice, setNotice] = useState("Loading skill sets…");
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [instructions, setInstructions] = useState("");
  const headers = useMemo(() => ({ Authorization: `Bearer ${token}`, "Content-Type": "application/json" }), [token]);
  const api = async (path: string, init: RequestInit = {}) => { const response = await fetch(`${base}${path}`, { ...init, headers: { ...headers, ...init.headers } }); const body = response.status === 204 ? null : await response.json().catch(() => null); if (!response.ok) throw new Error(body?.detail || "Request failed"); return body; };
  const load = async () => { try { setSkills(await api("/skills")); setNotice("Select one or more skills in chat when needed."); } catch (error) { setNotice((error as Error).message); } };
  const create = async () => { try { await api("/skills", { method: "POST", body: JSON.stringify({ name, description: description || null, instructions, is_published: false }) }); setName(""); setDescription(""); setInstructions(""); await load(); setNotice("Skill set created."); } catch (error) { setNotice((error as Error).message); } };
  const remove = async (id: string) => { if (!confirm("Delete this skill set?")) return; try { await api(`/skills/sets/${id}`, { method: "DELETE" }); await load(); } catch (error) { setNotice((error as Error).message); } };
  useEffect(() => { const saved = sessionStorage.getItem("ollama_gateway_token"); if (!saved) { router.replace("/login"); return; } setToken(saved); }, [router]);
  useEffect(() => { if (token) void load(); }, [token]);
  return <main className="min-h-screen bg-[#212121] p-5 text-[#ececec] md:p-8"><div className="mx-auto max-w-4xl"><header className="flex items-center justify-between border-b border-white/10 pb-6"><div><p className="text-xs font-semibold tracking-[.2em] text-slate-400">AI WORKFLOWS</p><h1 className="mt-2 text-3xl font-semibold">Skill sets</h1><p className="mt-2 text-sm text-slate-400">Reusable instructions you explicitly activate for a chat.</p></div><Link href="/chat" className="rounded-xl bg-white px-4 py-2 text-sm font-medium text-black">Back to chat</Link></header><p className="mt-4 text-sm text-slate-400">{notice}</p><section className="mt-6 rounded-2xl border border-white/10 bg-[#2a2a2a] p-5"><h2 className="font-semibold">Create personal skill set</h2><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Name, e.g. Secure code reviewer" className="mt-4 w-full rounded-lg border border-white/10 bg-black/20 p-3 outline-none" /><input value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Short description (optional)" className="mt-3 w-full rounded-lg border border-white/10 bg-black/20 p-3 outline-none" /><textarea value={instructions} onChange={(e) => setInstructions(e.target.value)} placeholder="Instructions for the AI. Keep them focused and within your authorized scope." className="mt-3 min-h-36 w-full rounded-lg border border-white/10 bg-black/20 p-3 outline-none" /><button onClick={() => void create()} disabled={!name.trim() || !instructions.trim()} className="mt-3 rounded-xl bg-sky-300 px-4 py-2.5 text-sm font-medium text-slate-950 disabled:bg-slate-600">Create skill set</button></section><section className="mt-6 grid gap-4 md:grid-cols-2">{skills.map((skill) => <article key={skill.id} className="rounded-2xl border border-white/10 bg-[#2a2a2a] p-5"><div className="flex justify-between gap-3"><h2 className="font-semibold">{skill.name}</h2>{skill.is_published && <span className="text-xs text-sky-200">Workspace</span>}</div><p className="mt-2 text-sm text-slate-400">{skill.description || "No description"}</p><p className="mt-4 whitespace-pre-wrap text-xs leading-5 text-slate-300">{skill.instructions}</p><button onClick={() => void remove(skill.id)} className="mt-4 text-sm text-rose-300">Delete</button></article>)}{!skills.length && <p className="text-sm text-slate-400">No skill sets yet.</p>}</section></div></main>;
}
